# Numpy Array

In [1]:
import numpy as np

In [2]:
a=np.array(["vignesh babu",1,2,3,4,5])
a

array(['vignesh babu', '1', '2', '3', '4', '5'], dtype='<U12')

In [3]:
type(a)

numpy.ndarray

In [4]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([1,2,3,4,5],ndmin=5)

array([[[[[1, 2, 3, 4, 5]]]]])

In [7]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
np.mat(np.array([1,2,3,4]))

matrix([[1, 2, 3, 4]])

In [10]:
np.mat("1 2 ; 3 4")

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [11]:
a=np.array([[1,2],[3,4]])

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
a[0]

array([1, 2])

In [14]:
a=[1,2]

In [15]:
np.asarray(a)

array([1, 2])

In [16]:
type(np.asarray(a))

numpy.ndarray

In [17]:
a=np.matrix([1,2])
a

matrix([[1, 2]])

In [18]:
np.asarray(a)

array([[1, 2]])

# np.asanyarray

In [19]:
a=[1,2]
a

[1, 2]

In [20]:
type(a)

list

In [21]:
np.asanyarray(a)

array([1, 2])

In [22]:
b=np.matrix([1,2])
b

matrix([[1, 2]])

In [23]:
np.asanyarray(b)

matrix([[1, 2]])

# COPY

#Shallow Copy

In [24]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [25]:
y=x

In [26]:
y

array([1, 2, 3])

In [27]:
x[0]

1

In [28]:
y[0]

1

#Deep Copy

In [29]:
x

array([1, 2, 3])

In [30]:
z=np.copy(x)

In [31]:
z

array([1, 2, 3])

In [32]:
z[0]=60

In [33]:
z

array([60,  2,  3])

In [34]:
x

array([1, 2, 3])

# numpy.fromfunction

In [35]:
np.fromfunction(lambda i, j: i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
np.fromfunction(lambda i,j : i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [37]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [38]:
np.fromiter(np.arange(10),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.fromstring("1 2",sep=" ")

array([1., 2.])

In [40]:
np.fromstring("1,2",sep=" ,",dtype=int)

array([1, 2])

# DataTypes

In [41]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [42]:
b=np.array(a)
b

array([1, 2, 3, 4])

In [43]:
b.ndim

1

In [44]:
b.size

4

In [45]:
b.shape

(4,)

In [46]:
b.dtype

dtype('int32')

In [47]:
b=([[1,2.0],[2,3,0]])
b

[[1, 2.0], [2, 3, 0]]

In [48]:
np.array(b)

array([list([1, 2.0]), list([2, 3, 0])], dtype=object)

# arange and linspace

In [49]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [50]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [53]:
np.arange(50,-1,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [57]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# Matrix Creation

In [58]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [64]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [65]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
np.ones((5,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [69]:
np.ones((5,2,20))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]]])

In [70]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [71]:
np.empty((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [72]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
np.logspace(1,20,4,base=10)

array([1.00000000e+01, 2.15443469e+07, 4.64158883e+13, 1.00000000e+20])

# Diagonal Matrix

In [76]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
b=x.reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
np.diag(b)

array([ 0,  5, 10, 15])

In [84]:
np.diag(np.diag(b))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [81]:
np.diag(b,k=1)

array([ 1,  6, 11])

In [82]:
np.diag(b,k=2)

array([2, 7])

In [83]:
np.diag(b,k=-1)

array([ 4,  9, 14])

In [86]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [87]:
np.diagflat([1,2],2)

array([[0, 0, 1, 0],
       [0, 0, 0, 2],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [89]:
np.tri(3,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [90]:
np.tri(3,5,k=2)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [92]:
np.tri(3,5,k=3)

array([[1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
np.tri(3,5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [93]:
np.tri(9,9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [94]:
np.tri(9,9,2)

array([[1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [95]:
np.tri(9,9,-2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0.]])

In [108]:
np.tril([[3,5,3],[4,5,6],[7,8,9]])

array([[3, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [105]:
np.tril([[3,5,3],[4,5,6],[7,8,9]],1)

array([[3, 5, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
np.triu([[3,5,3],[4,5,6],[7,8,9]],1)

array([[0, 5, 3],
       [0, 0, 6],
       [0, 0, 0]])

# Random Number Generation

In [116]:
np.random.randn(2,3)

array([[ 1.49107667,  0.2918782 ,  0.17545079],
       [ 0.12495285, -0.30540463, -0.74674719]])

In [120]:
np.random.randint(2,100,5)

array([28, 89, 25, 39, 40])

# Reshaping

In [121]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[ 7, 12, 81, 10, 28],
       [84, 82, 27, 47, 55],
       [69,  1, 60, 62, 93],
       [12, 69, 58, 77,  9],
       [88, 45, 99, 63, 51],
       [20, 73, 22, 47, 70]])

In [122]:
a.shape

(30,)

In [123]:
b.shape

(2, 3, 5)

In [124]:
c.shape

(6, 5)

# indexing and slicing

In [125]:
arr = np.arange(0,11)
print("Array:",arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [126]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [127]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


# subsetting

In [128]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[83 91 96 67 27]
 [39 10 40 88 42]
 [82 72 47 27 24]]


array([[ True,  True,  True,  True, False],
       [False, False, False,  True, False],
       [ True,  True, False, False, False]])

In [129]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[83 91]
 [39 10]]

Change the sliced matrix


# universal functions 

In [130]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 9 2]
 [1 9 6]
 [3 8 2]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[5 9 4]
 [7 8 3]
 [7 3 2]]


In [131]:
mat1*mat2

array([[15, 81,  8],
       [ 7, 72, 18],
       [21, 24,  4]])

In [132]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 92 105  43]
 [110  99  43]
 [ 85  97  40]]


In [133]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\ADMIN\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [134]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[103 109 102]
 [101 109 106]
 [103 108 102]]


In [135]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27 729   8]
 [  1 729 216]
 [ 27 512   8]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27 729   8]
 [  1 729 216]
 [ 27 512   8]]


In [136]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27 729   8]
 [  1 729 216]
 [ 27 512   8]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27 729   8]
 [  1 729 216]
 [ 27 512   8]]


# Broadcasting

In [137]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [138]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [139]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [140]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [141]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [142]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [143]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[1 7 2]
 [4 3 6]
 [2 1 5]]

2nd Matrix of random single-digit numbers
------------
 [[1 4 4]
 [4 5 5]
 [1 7 3]]


In [144]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[1.         2.64575131 1.41421356]
 [2.         1.73205081 2.44948974]
 [1.41421356 1.         2.23606798]]


In [145]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[   2.71828183 1096.63315843    7.3890561 ]
 [  54.59815003   20.08553692  403.42879349]
 [   7.3890561     2.71828183  148.4131591 ]]


In [146]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.         0.84509804 0.30103   ]
 [0.60205999 0.47712125 0.77815125]
 [0.30103    0.         0.69897   ]]
[[1 7 2]
 [4 3 6]
 [2 1 5]]
[[1 4 4]
 [4 5 5]
 [1 7 3]]


In [147]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[0 3 2]
 [0 3 1]
 [0 1 2]]


array([[0, 3, 2],
       [0, 3, 1],
       [0, 1, 2]], dtype=int32)