# Numpy Array

In [1]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [2]:
#Upcasting:

In [3]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [4]:
#two dimensions

In [5]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [7]:
#Minimum dimensions 2:

In [8]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [9]:
#dtype

In [10]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
#Data-type consisting of more than one element:

In [12]:
x = np.array([(1,2),(3,4)])
x

array([[1, 2],
       [3, 4]])

In [13]:
x[0][0]

1

In [14]:
x[0][1]

2

In [15]:
x[1][0]

3

In [16]:
x[1][1]

4

In [17]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i4')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i4')])

In [18]:
type(x[0][1])#i2 is 16 bit operation

numpy.int32

In [19]:
#i2 is 16 bit operation
#i4 is 32 bit operation
#i8 is 64 bit operation

In [20]:
type(x[0][1])#i8 is 16 bit operation

numpy.int32

In [21]:
type(x[1][0])

numpy.int16

In [22]:

#Creating an array from sub-classes:

In [23]:
np.array([[1, 2],[4,7]])

array([[1, 2],
       [4, 7]])

In [24]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [25]:
# ndarray subclasses are not passed through
issubclass(np.matrix, np.ndarray)

True

In [26]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [27]:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

# numpy.asarray

In [28]:
#Convert the input to an array.

In [29]:
#Convert a list into an array:

In [30]:
 a = [1, 2]
type(a)

list

In [31]:
np.asarray(a)

array([1, 2])

In [32]:
type(np.asarray(a))

numpy.ndarray

In [33]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [34]:
np.asarray((1,2))

array([1, 2])

In [35]:
#If dtype is set, array is copied only if dtype does not match:

In [36]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [37]:
#np.asarray([1,2]) is a

In [38]:
np.asarray([1,2])

array([1, 2])

In [39]:
#np.asarray(a, dtype=np.float64) is a

In [40]:
# ndarray subclasses are not passed through

In [41]:
#matrix is the subclass of array
#array is not the sub class of matrix

In [42]:
issubclass(np.matrix, np.ndarray)

True

In [43]:
issubclass(np.ndarray,np.matrix)

False

In [44]:
#a = np.matrix([[1, 2]])
#np.asanyarray(a)

In [45]:
#np.asarray(a) is a

In [46]:
#np.asanyarray(a) is a

In [47]:
#type(np.asarray(a))

# numpy.asanyarray

In [48]:
#np.array will convert non array format in to array format and convert array format in to again array format
#np.asarray will convert non array format in to array format and convert array format in to again array format
#np.asarray will convert non array format in to array format and and not convert array format in to again array format

In [49]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [50]:
b = np.matrix([1, 2])
b

matrix([[1, 2]])

In [51]:
np.asanyarray(b)

matrix([[1, 2]])

In [52]:
#np.asanyarray([1,2]) is a

# Numpy Copy Functions

# Shallow Copy

In [53]:
a=[1,2,3,4,5]

In [54]:
b=a

In [55]:
a[0]=10

In [56]:
a

[10, 2, 3, 4, 5]

In [57]:
b

[10, 2, 3, 4, 5]

# Deep Copy

In [58]:
a=[1,2,3,4,5]

In [59]:
b=np.copy(a)

In [60]:
a[0]=10

In [61]:
a

[10, 2, 3, 4, 5]

In [62]:
b

array([1, 2, 3, 4, 5])

# numpy.fromfunction

In [63]:
#Construct an array by executing a function over each coordinate.

In [64]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [65]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [66]:
#(4, 3,3) it will create 3*3 matrix 4 times with 3 dimensional array

In [67]:
np.fromfunction(lambda i, j,k: i * j*k ,(4, 3,3), dtype=int)

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  1,  2],
        [ 0,  2,  4]],

       [[ 0,  0,  0],
        [ 0,  2,  4],
        [ 0,  4,  8]],

       [[ 0,  0,  0],
        [ 0,  3,  6],
        [ 0,  6, 12]]])

In [68]:
#Create a new 1-dimensional array from an iterable object.

In [69]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001E320BA3648>

In [70]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [71]:
#A new 1-D array initialized from text data in a string

In [72]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [73]:
np.fromstring('1 ,2',dtype=int, sep=',')

array([1, 2])

In [74]:
# How to create create a record array from a (flat) list of arrays

In [75]:
x1=np.array([1,2,3,4])

In [76]:
x2=np.array(['a','dd','xyz','12'])

In [77]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [78]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [79]:
r[1][0]

2

In [80]:
print(r[1]["a"])

2


In [81]:
x1[1]=34

In [82]:
x1[1]

34

# data types

In [83]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [84]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [85]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")

Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [86]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [87]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [88]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [89]:
list(range(50,0,-1))

[50,
 49,
 48,
 47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13,
 12,
 11,
 10,
 9,
 8,
 7,
 6,
 5,
 4,
 3,
 2,
 1]

In [90]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [91]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [92]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [93]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [94]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [95]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [96]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [97]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples

Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [98]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [99]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [100]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [101]:
np.arange(3)

array([0, 1, 2])

In [102]:
np.arange(3.0)

array([0., 1., 2.])

In [103]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [104]:
np.arange(3,7,2)

array([3, 5])

In [105]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [106]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [107]:
np.linspace(2.0, 3.0, num=9, retstep=True)#retstep shows end point between the array

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [108]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [109]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [110]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [111]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [112]:
#Extract a diagonal or construct a diagonal array.

In [113]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [114]:
x = np.arange(16).reshape((-1,4))

In [115]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
np.diag(x)

array([ 0,  5, 10, 15])

In [117]:
np.diag(x, k=2)

array([2, 7])

In [118]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [119]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [120]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [121]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [122]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [123]:
np.diagflat([1,2], -1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

In [124]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [125]:
np.tri(3, 3, dtype=int)

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [126]:
np.tri(3, 3,1, dtype=int)

array([[1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [127]:
np.tri(3, 3,2, dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [128]:
np.tri(3, 5, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [129]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [130]:
np.tri(3, 5, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [131]:
np.tri(3, 5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0]])

In [132]:
#return a Lower triangle of an array.

In [133]:
np.mat([[1,2,3],[4,5,6],[7,8,9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [134]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [135]:
#return Upper triangle of an array.

In [136]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [195]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.64951781 0.10818377 0.16058945]
 [0.40711312 0.63676936 0.36650156]]


In [209]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[[0.18385072 0.47835245 0.97027203]
  [0.36529785 0.25846103 0.26190584]
  [0.23451488 0.72609038 0.09323636]]

 [[0.16681063 0.42524194 0.01595126]
  [0.05504307 0.8184062  0.24734224]
  [0.00365067 0.97676971 0.68119228]]]


In [196]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.38782829  0.31100743  1.20162496]
 [ 0.86699783  0.22846945 -1.7793447 ]
 [-0.38957721  0.99476579  0.99241995]
 [-0.52090245  0.11693763 -0.65102972]]


In [210]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")

Random integer vector: 9

Random integer matrix


In [211]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[37 56 59 18]
 [43 99 96 96]
 [23 66 93 12]
 [69 80  1 33]]

20 samples drawn from a dice throw: [3 4 2 4 2 2 5 3 2 1 2 4 4 5 3 4 2 5 5 4]


In [212]:
np.random.randint(1,100,(3,4,4))

array([[[ 7,  3, 91, 67],
        [10,  5, 13, 79],
        [80, 28, 91, 41],
        [43, 45, 50, 39]],

       [[13, 80, 35, 65],
        [78, 64, 99, 47],
        [57, 77, 60, 31],
        [19, 13, 82, 22]],

       [[69, 20, 62, 54],
        [44, 50, 45, 33],
        [44, 12, 65, 94],
        [93, 49, 36, 66]]])

# Reshaping

In [213]:
ri(1,100,30)

array([61, 77, 47, 27, 30, 24, 66, 85, 99, 80, 82, 29, 56, 15, 94, 73, 53,
       62, 63, 90, 45, 72, 64, 85, 39, 32, 51, 28,  1, 81])

In [215]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
b

array([[[26, 72, 53, 84, 92],
        [60, 73, 28, 94, 95],
        [67, 77, 15, 15, 29]],

       [[75, 45, 86, 84, 72],
        [12, 83,  5, 46, 24],
        [61,  1,  5, 50, 43]]])

In [216]:
c

array([[26, 72, 53, 84, 92],
       [60, 73, 28, 94, 95],
       [67, 77, 15, 15, 29],
       [75, 45, 86, 84, 72],
       [12, 83,  5, 46, 24],
       [61,  1,  5, 50, 43]])

In [217]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [218]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


a looks like
 -------------------- 
 [26 72 53 84 92 60 73 28 94 95 67 77 15 15 29 75 45 86 84 72 12 83  5 46
 24 61  1  5 50 43] 
 --------------------

b looks like
 -------------------- 
 [[[26 72 53 84 92]
  [60 73 28 94 95]
  [67 77 15 15 29]]

 [[75 45 86 84 72]
  [12 83  5 46 24]
  [61  1  5 50 43]]] 
 --------------------

c looks like
 -------------------- 
 [[26 72 53 84 92]
 [60 73 28 94 95]
 [67 77 15 15 29]
 [75 45 86 84 72]
 [12 83  5 46 24]
 [61  1  5 50 43]] 
 --------------------


In [219]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [43 20 49 47 66 80 51 47 36 27]

Here is the sorted vector
 -------------------------------------------------- 
 [20 27 36 43 47 47 49 51 66 80]


In [226]:
M = ri(1,100,25).reshape(5,5)
M

array([[30, 49, 96, 73, 98],
       [83, 67, 34, 85, 17],
       [19, 90, 17, 19, 13],
       [86, 96, 97, 36, 69],
       [54, 66, 79, 42, 64]])

In [221]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[23 34 34 67 90]
 [ 3 55 73 74 77]
 [21 27 42 43 51]
 [ 4 37 43 52 71]
 [27 29 44 48 92]]


array([[23, 34, 90, 67, 34],
       [74, 73,  3, 77, 55],
       [21, 42, 51, 27, 43],
       [52, 71, 37,  4, 43],
       [48, 92, 29, 44, 27]])

In [227]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 2 12  3 15 32]
 [13 47 12 47 35]
 [23 76 69 61 64]
 [51 83 74 70 78]
 [68 85 99 76 84]]


array([[ 2, 76, 99, 70, 32],
       [13, 47, 69, 47, 64],
       [23, 12, 74, 15, 84],
       [68, 83, 12, 61, 35],
       [51, 85,  3, 76, 78]])

In [229]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 99
Max of b: 95


array([[[26, 72, 53, 84, 92],
        [60, 73, 28, 94, 95],
        [67, 77, 15, 15, 29]],

       [[75, 45, 86, 84, 72],
        [12, 83,  5, 46, 24],
        [61,  1,  5, 50, 43]]])

In [230]:
M

array([[ 2, 76, 99, 70, 32],
       [13, 47, 69, 47, 64],
       [23, 12, 74, 15, 84],
       [68, 83, 12, 61, 35],
       [51, 85,  3, 76, 78]])

In [231]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [2 2 4 1 1]
Max of b location: 9
Max of c location: 9


# Indexing and slicing

In [232]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [233]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [234]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [235]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [236]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [250]:
arr[1:-5:2]

array([1, 3, 5])

In [242]:
print("Elements from last backwards are:", arr[-1:7:-1])

Elements from last backwards are: [10  9  8]


In [239]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [251]:
print("3 Elements from last backwards are:", arr[-1:-6:2])

3 Elements from last backwards are: []


In [252]:
arr = np.arange(0,21,2)
print("New array:",arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [253]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [269]:
mat = np.array(ri(10,100,45)).reshape(3,5,3)
mat

array([[[72, 54, 87],
        [84, 92, 10],
        [32, 68, 62],
        [95, 25, 84],
        [85, 29, 70]],

       [[75, 44, 12],
        [39, 10, 39],
        [90, 24, 14],
        [12, 91, 67],
        [55, 45, 60]],

       [[30, 65, 80],
        [40, 25, 68],
        [62, 27, 71],
        [11, 63, 10],
        [18, 13, 27]]])

In [270]:
mat[0]

array([[72, 54, 87],
       [84, 92, 10],
       [32, 68, 62],
       [95, 25, 84],
       [85, 29, 70]])

In [273]:
mat[0][1]

array([84, 92, 10])

In [274]:
mat[0][1][0]

84

In [275]:
mat

array([[[72, 54, 87],
        [84, 92, 10],
        [32, 68, 62],
        [95, 25, 84],
        [85, 29, 70]],

       [[75, 44, 12],
        [39, 10, 39],
        [90, 24, 14],
        [12, 91, 67],
        [55, 45, 60]],

       [[30, 65, 80],
        [40, 25, 68],
        [62, 27, 71],
        [11, 63, 10],
        [18, 13, 27]]])

In [277]:
mat[0][:,1]

array([54, 92, 68, 25, 29])

In [262]:
mat[1:4,3:5]

array([[86, 79],
       [66, 54]])

In [278]:
mat

array([[[72, 54, 87],
        [84, 92, 10],
        [32, 68, 62],
        [95, 25, 84],
        [85, 29, 70]],

       [[75, 44, 12],
        [39, 10, 39],
        [90, 24, 14],
        [12, 91, 67],
        [55, 45, 60]],

       [[30, 65, 80],
        [40, 25, 68],
        [62, 27, 71],
        [11, 63, 10],
        [18, 13, 27]]])

In [281]:
mat[0:2]

array([[[72, 54, 87],
        [84, 92, 10],
        [32, 68, 62],
        [95, 25, 84],
        [85, 29, 70]],

       [[75, 44, 12],
        [39, 10, 39],
        [90, 24, 14],
        [12, 91, 67],
        [55, 45, 60]]])

In [282]:
mat

array([[[72, 54, 87],
        [84, 92, 10],
        [32, 68, 62],
        [95, 25, 84],
        [85, 29, 70]],

       [[75, 44, 12],
        [39, 10, 39],
        [90, 24, 14],
        [12, 91, 67],
        [55, 45, 60]],

       [[30, 65, 80],
        [40, 25, 68],
        [62, 27, 71],
        [11, 63, 10],
        [18, 13, 27]]])

In [285]:
mat[0:2]

array([[[72, 54, 87],
        [84, 92, 10],
        [32, 68, 62],
        [95, 25, 84],
        [85, 29, 70]],

       [[75, 44, 12],
        [39, 10, 39],
        [90, 24, 14],
        [12, 91, 67],
        [55, 45, 60]]])

In [286]:
mat[0:2,[1,3]]

array([[[84, 92, 10],
        [95, 25, 84]],

       [[39, 10, 39],
        [12, 91, 67]]])

In [254]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[25 21 52 23 30]
 [43 53 26 72 26]
 [84 87 39 90 32]]


array([[21, 23],
       [53, 72],
       [87, 90]])

In [255]:
mat[0:3,[1,3]]
mat

array([[25, 21, 52, 23, 30],
       [43, 53, 26, 72, 26],
       [84, 87, 39, 90, 32]])

In [159]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 52


array([[70, 93, 35, 48, 73],
       [89, 52, 14, 47, 35],
       [26, 87, 19, 71, 85]])

In [160]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 14

Row or column extract
----------------------


In [161]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [26 87 19 71 85]
Entire column at index 3: [48 47 71]


In [162]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[47 35]
 [71 85]]


In [163]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[93 48]
 [52 47]]


# Subseting

In [287]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[61 31 47 65 47]
 [14 23 96 65 99]
 [26 34 14 73 68]]


array([[ True, False, False,  True, False],
       [False, False,  True,  True,  True],
       [False, False, False,  True,  True]])

In [288]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [61 65 96 65 99 73 68]


# Slicing

In [290]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [291]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [292]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [293]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [294]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [295]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [296]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [297]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [309]:
a = np.array(ri(1,10,9)).reshape(3,3)
b = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",a)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",b)


1st Matrix of random single-digit numbers
----------------------------------------
 [[7 8 8]
 [2 8 8]
 [8 8 2]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 5 4]
 [7 3 5]
 [2 5 6]]


In [310]:
a*b

array([[42, 40, 32],
       [14, 24, 40],
       [16, 40, 12]])

In [311]:
a

array([[7, 8, 8],
       [2, 8, 8],
       [8, 8, 2]])

In [312]:
b

array([[6, 5, 4],
       [7, 3, 5],
       [2, 5, 6]])

In [313]:
a+b

array([[13, 13, 12],
       [ 9, 11, 13],
       [10, 13,  8]])

In [314]:
a@b

array([[114,  99, 116],
       [ 84,  74,  96],
       [108,  74,  84]])

In [315]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", a@b)



Multiplication
------------------
 [[114  99 116]
 [ 84  74  96]
 [108  74  84]]


In [316]:
print("\nDivision\n------------------\n", a/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\ADMIN\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [317]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+a)



Addition of a scalar (100)
-------------------------
 [[107 108 108]
 [102 108 108]
 [108 108 102]]


In [318]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", a**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(a,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[343 512 512]
 [  8 512 512]
 [512 512   8]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[343 512 512]
 [  8 512 512]
 [512 512   8]]


# Broadcasting

In [180]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [319]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [320]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [321]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [322]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [323]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [324]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [325]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


1st Matrix of random single-digit numbers

 [[7 5 7]
 [6 4 2]
 [7 9 8]]

2nd Matrix of random single-digit numbers
------------
 [[3 3 4]
 [7 8 9]
 [3 5 6]]


In [326]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.64575131 2.23606798 2.64575131]
 [2.44948974 2.         1.41421356]
 [2.64575131 3.         2.82842712]]


In [327]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.09663316e+03 1.48413159e+02 1.09663316e+03]
 [4.03428793e+02 5.45981500e+01 7.38905610e+00]
 [1.09663316e+03 8.10308393e+03 2.98095799e+03]]


In [328]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.84509804 0.69897    0.84509804]
 [0.77815125 0.60205999 0.30103   ]
 [0.84509804 0.95424251 0.90308999]]
[[7 5 7]
 [6 4 2]
 [7 9 8]]
[[3 3 4]
 [7 8 9]
 [3 5 6]]


In [329]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[1 2 3]
 [6 4 2]
 [1 4 2]]


array([[1, 2, 3],
       [6, 4, 2],
       [1, 4, 2]], dtype=int32)

In [330]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [331]:
A = np.linspace(0,12*np.pi,1001)


In [332]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])